#!/usr/bin/env bash

## Download and setup Adminer into the container for easier SQL access.
##
## Usage: dsh adminer
##

source ${PROJECT_ROOT}/.docksal/command-settings
echo-yellow ${PROJECT_ROOT}
ensure_containers_up

echo-green "Setting up Adminer"
cd ${PROJECT_ROOT}/docroot
echo-yellow "I need to alter the .htaccess file to allow adminer, which is a PHP script, to execute."
rm -rf adminer
mkdir adminer
cd adminer
touch .htaccess
fin run echo '#Allow access to adminer
 RewriteCond %{REQUEST_URI} !/adminer/index.php$' > .htaccess
wget -O index.php https://gist.githubusercontent.com/TLyngeJ/42195aefee585d5637944ee93e3d8792/raw/530eb310c871957e0d029b51cf88ed1be76dca81/index.php  &> /dev/null
wget -O adminer.php https://www.adminer.org/static/download/4.2.5/adminer-4.2.5-mysql-en.php &> /dev/null
echo-green "You can now access you database from http://${SITE_DOMAIN}/adminer"
