#!/usr/bin/env bash

## Imports DB from specified environment. Downloads dump where required
##
## Usage: fin db-import
##         --fetch Force download
##

source ${DOCKSAL_PATH}/.docksal/command-settings

ensure_containers_up

echo-green "saving database"
fin drush sql-dump > ${DOCKSAL_PATH}/db/database-backup.sql
echo-green "Database imported"
