#!/usr/bin/env bash

## Downloads DB from specified environment.
##
## Usage: fin db-download [environment]
##         --fetch Force download
##

source $PROJECT_ROOT/.docksal/command-settings

# Check for set vars
if [[ -z $1 || $1 == "--fetch" ]]; then
  echo-red "Command failed: You must include the environment to download from"
  exit
fi

file_name=$1

if [[ ! -f ${PROJECT_ROOT}/db/${file_name}.sql  || $2 == "--fetch" ]]; then
  cd ${PROJECT_ROOT}
  echo-green "Downloading ${file_name} DB"

  platform db:dump -p ${PLATFORM_ID} -e ${file_name} -y -f db/${file_name}.sql
else
  echo-green "Using local copy of ${file_name} DB"
fi
