#!/usr/bin/env bash

## Enable or disable developer tools on the site
##
## Usage: fin devel enable|disable
##           enable      Enable developer tools known to the site
##           disable     Disable developer tools


source ${DOCKSAL_PATH}/.docksal/command-settings

ensure_containers_up

cd ${DOCROOT_PATH}

if [[ $1 == "enable" ]]; then
  fin drush en -y devel config_inspector webprofiler
  # Config devel is know to cause issues when uninstalling.
  # It is therefore not enabled by default.
  #fin drush en -y config_devel 
  fin drush cset -y devel.settings devel_dumper var_dumper 
fi

if [[ $1 == "disable" ]]; then
  fin drush pmu -y webprofiler
  fin drush pmu -y devel config_inspector config_devel
fi
