#!/usr/bin/env bash

## Sync files from local sites/default/files folder to master site.
##
## Usage: fin files-download
##

source ${DOCKSAL_PATH}/.docksal/command-settings

cd ${DOCROOT_PATH}

rsync -rvz --exclude 'js' --exclude 'css' --exclude 'php' --exclude 'ctools' --progress --size-only myrepo@myrepo.com:/app/web/sites/default/files/. sites/default/files/
