#!/usr/bin/env bash

## Copies config files for local environment.
##
## Usage: fin local-config
##           --no-cache      Use no-cache config files.
##           --force          Forces an overwrite of all files including docker-compose.yml
##

source ${DOCKSAL_PATH}/.docksal/command-settings

# Copy environment config
copy_environment_configuration $1 $2
