#!/usr/bin/env bash

## Copies config files which turn off all caching.
##
## Usage: fin no-cache-config
##

source ${DOCKSAL_PATH}/.docksal/command-settings

# Copy environment no-cache config
echo-yellow "Copying no-cache settings.local.php file"
chmod 664 ${SITEDIR_PATH}/settings.local.php
cp "${PROJECT_ROOT}/.docksal/template.nocache.settings.local.php" "${SITEDIR_PATH}/settings.local.php"

echo-yellow "Copying development.services.yml file"
cp "${PROJECT_ROOT}/.docksal/template.development.services.yml" "${SITEDIR_PATH}/development.services.yml"
