#!/usr/bin/env bash

## Run npm in the theme folder.
##
## Usage: fin npm [command]
##

source ${DOCKSAL_PATH}/.docksal/command-settings

ensure_containers_up

# Run npm command
fin exec npm $1 $2 $3 $4 $5 $6
